# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MÄRTAS VÄRLD
email: cool@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Välkommen till Märtas värld! Detta är en hemsida som jag själv har programmerat. Det är anledningen till
att den inte är så vacker. Men oroa er inte, jag jobbar på det. Hoppas att du
som besöker hemsidan tycker att den är fin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: cool_tjej
github_username:  cool_tjej

# Build settings
markdown: kramdown
